[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/kanaemi-app/kanaemi-dict"

[workspace.dependencies]
kanaemi-core = { git = "https://github.com/kanaemi-app/kanaemi", rev = "c6acad960b025a6cfbbe227d9129c0c96e77cb11" }
kanaemi-engine = { git = "https://github.com/kanaemi-app/kanaemi", rev = "c6acad960b025a6cfbbe227d9129c0c96e77cb11" }
kanaemi-functions = { git = "https://github.com/kanaemi-app/kanaemi", rev = "c6acad960b025a6cfbbe227d9129c0c96e77cb11" }
